---
# Default Tackle 2 endpoint and credentials
url: http://REPLACE_SVC:8080
username: REPLACE_USER
password: REPLACE_PASSWORD
# Passphrase to decrypt exported data.
# Empty for unencrypted data
encryption_passphrase:
# And again with typo in key
encryption_passphase:
